# Site wide configuration

title: Marianna Bezler Notes
locale: en_US
description: Work in progress. Check Rainbow Memories.
logo: avatar-circle.jpg
search: true
#url: http://localhost:4000
#url: http://nefry.github.io/marianna.im
url: http://marianna.im

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Marianna Bezler
  avatar: avatar-circle.jpg
  email: marianna.bezler@gmail.com
  disqus-shortname:
  twitter: MaryanaBezler
  github: Nefry
  linkedin: mariannabezler
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot: